name: english_kids
description: Англисиро Омӯз — барномаи муосири омӯзиши англисӣ барои кӯдакони тоҷик.
publish_to: "none"
version: 1.0.0+10

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.3
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.5.0
  android_alarm_manager_plus: ^4.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - data/vocabulary.json
    - assets/logo.svg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/launcher.png"
  min_sdk_android: 21
  adaptive_icon_background: "#020617"
  adaptive_icon_foreground: "assets/launcher.png"
