#!/usr/bin/env python3
"""Expand bundled vocabulary to 500 unique entries without changing existing ids."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "data" / "vocabulary.json"

EXTRAS: list[tuple[str, str, str, int, str, str, str]] = [
    # week 1 +25
    ("sorry", "сорри", "бубахшед", 1, "Greetings", "I am sorry.", "Ман бубахшед мегӯям."),
    ("excuse me", "икскюз ми", "мебахшед", 1, "Greetings", "Excuse me, please.", "Мебахшед, лутфан."),
    ("welcome", "уэлкам", "хуш омадед", 1, "Greetings", "Welcome to class!", "Хуш омадед ба дарс!"),
    ("friend", "френд", "дӯст", 1, "Feelings", "You are my friend.", "Ту дӯсти ман ҳастӣ."),
    ("boy", "бой", "писар", 1, "Basics", "The boy is happy.", "Писар хушҳол аст."),
    ("girl", "гёрл", "духтар", 1, "Basics", "The girl is kind.", "Духтар меҳрубон аст."),
    ("child", "чайлд", "кӯдак", 1, "Basics", "I am a child.", "Ман кӯдак ҳастам."),
    ("smile", "смайл", "табассум", 1, "Feelings", "Please smile.", "Лутфан табассум кунед."),
    ("laugh", "лаф", "хандидан", 1, "Feelings", "We laugh together.", "Мо якҷо ханда мекунем."),
    ("cry", "край", "гиристаан", 1, "Feelings", "Do not cry.", "Нагир."),
    ("love", "лав", "дӯст доштан", 1, "Feelings", "I love my family.", "Ман оилаамро дӯст медорам."),
    ("like", "лайк", "маъқул будан", 1, "Feelings", "I like English.", "Ба ман англисӣ маъқул аст."),
    ("good", "гуд", "хуб", 1, "Feelings", "This is good.", "Ин хуб аст."),
    ("bad", "бэд", "бад", 1, "Feelings", "That is bad.", "Он бад аст."),
    ("nice", "найс", "хуб / зебо", 1, "Feelings", "You are nice.", "Ту хуб ҳастӣ."),
    ("kind", "кайнд", "меҳрубон", 1, "Feelings", "Be kind.", "Меҳрубон бош."),
    ("funny", "фани", "хандаовар", 1, "Feelings", "The joke is funny.", "Шӯхӣ хандаовар аст."),
    ("brave", "брейв", "шуҷоъ", 1, "Feelings", "The girl is brave.", "Духтар шуҷоъ аст."),
    ("help", "ҳэлп", "ёрӣ додан", 1, "Basics", "Please help me.", "Лутфан ба ман ёрӣ диҳед."),
    ("stop", "стоп", "истодан / бас", 1, "Basics", "Stop, please.", "Ист, лутфан."),
    ("wait", "уэйт", "интизор шудан", 1, "Basics", "Wait a minute.", "Як дақиқа интизор шав."),
    ("ok", "окей", "хуб / майлаш", 1, "Greetings", "OK, let's go.", "Хуб, рафтем."),
    ("wow", "уау", "вой", 1, "Feelings", "Wow, a star!", "Вой, ситора!"),
    ("hello friend", "ҳэллоу френд", "салом дӯст", 1, "Greetings", "Hello, friend!", "Салом, дӯст!"),
    ("see you", "си ю", "то дидор", 1, "Greetings", "See you tomorrow.", "То пагоҳ."),
    # week 2 +25
    ("eleven", "илэвн", "ёздаҳ", 2, "Numbers", "I am eleven.", "Ман ёздаҳсола ҳастам."),
    ("twelve", "туэлв", "дувоздаҳ", 2, "Numbers", "There are twelve eggs.", "Дувоздаҳ тухм ҳаст."),
    ("thirteen", "сёртин", "сездаҳ", 2, "Numbers", "Thirteen birds fly.", "Сездаҳ парранда парвоз мекунанд."),
    ("fourteen", "фортин", "чордаҳ", 2, "Numbers", "I see fourteen cars.", "Ман чордаҳ мошин мебинам."),
    ("fifteen", "фифтин", "понздаҳ", 2, "Numbers", "Fifteen is a number.", "Понздаҳ як рақам аст."),
    ("sixteen", "сикстин", "шонздаҳ", 2, "Numbers", "She is sixteen.", "Ӯ шонздаҳсола аст."),
    ("seventeen", "сэвнтин", "ҳабдаҳ", 2, "Numbers", "Seventeen books.", "Ҳабдаҳ китоб."),
    ("eighteen", "эйтин", "ҳаждаҳ", 2, "Numbers", "Eighteen chairs.", "Ҳаждаҳ курсӣ."),
    ("nineteen", "найнтин", "нуздаҳ", 2, "Numbers", "Nineteen trees.", "Нуздаҳ дарахт."),
    ("twenty", "туэнти", "бист", 2, "Numbers", "I can count to twenty.", "Ман то бист ҳисоб карда метавонам."),
    ("round", "раунд", "гирд", 2, "Shapes", "The ball is round.", "Тӯб гирд аст."),
    ("square", "скуэр", "чоркунҷа", 2, "Shapes", "A square has four sides.", "Чоркунҷа чор тараф дорад."),
    ("triangle", "трайэнгл", "секунҷа", 2, "Shapes", "Draw a triangle.", "Секунҷа кашед."),
    ("star", "стар", "ситора", 2, "Shapes", "A star is bright.", "Ситора дурахшон аст."),
    ("dark", "дарк", "торик", 2, "Colors", "The night is dark.", "Шаб торик аст."),
    ("light", "лайт", "равшан / нур", 2, "Colors", "The room is light.", "Ҳуҷра равшан аст."),
    ("bright", "брайт", "дурахшон", 2, "Colors", "The sun is bright.", "Офтоб дурахшон аст."),
    ("many", "мэни", "зиёд", 2, "Numbers", "I have many toys.", "Ман бозичаҳои зиёд дорам."),
    ("few", "фю", "кам", 2, "Numbers", "A few apples.", "Чанд себи кам."),
    ("more", "мор", "бештар", 2, "Numbers", "I want more water.", "Ман оби бештар мехоҳам."),
    ("less", "лес", "камтар", 2, "Numbers", "Less sugar, please.", "Қанди камтар, лутфан."),
    ("first", "фёрст", "аввал", 2, "Numbers", "I am first.", "Ман аввал ҳастам."),
    ("last", "ласт", "охирин", 2, "Numbers", "She is last.", "Ӯ охирин аст."),
    ("next", "некст", "баъдӣ", 2, "Numbers", "Who is next?", "Кӣ навбатӣ аст?"),
    ("number", "намбер", "рақам", 2, "Numbers", "What number is this?", "Ин кадом рақам аст?"),
    # week 3 +20
    ("aunt", "ант", "амма / хола", 3, "Family", "My aunt is kind.", "Аммаам меҳрубон аст."),
    ("uncle", "анкл", "амак / тағо", 3, "Family", "My uncle is tall.", "Амакам қадбаланд аст."),
    ("cousin", "казн", "ҷиян", 3, "Family", "This is my cousin.", "Ин ҷияни ман аст."),
    ("son", "сан", "писар (фарзанд)", 3, "Family", "He is their son.", "Ӯ писари онҳост."),
    ("daughter", "дотер", "духтар (фарзанд)", 3, "Family", "She is their daughter.", "Ӯ духтари онҳост."),
    ("parents", "пэрэнтс", "падару модар", 3, "Family", "I love my parents.", "Ман падару модарамро дӯст медорам."),
    ("people", "пипл", "одамон", 3, "Family", "Many people smile.", "Одамони зиёд табассум мекунанд."),
    ("home", "ҳоум", "хона (ҷои зист)", 3, "Home", "I go home.", "Ман ба хона меравам."),
    ("house", "ҳаус", "хона (бино)", 3, "Home", "Our house is small.", "Хонаи мо хурд аст."),
    ("shoulder", "шоулдер", "кифт", 3, "Body", "My shoulder hurts.", "Кифтам дард мекунад."),
    ("knee", "ни", "зону", 3, "Body", "Bend your knee.", "Зонуятро хам кун."),
    ("neck", "нек", "гардан", 3, "Body", "A scarf on my neck.", "Дар гарданам рӯймол."),
    ("face", "фейс", "рӯй", 3, "Body", "Wash your face.", "Рӯятро шӯй."),
    ("skin", "скин", "пӯст", 3, "Body", "Skin can be brown.", "Пӯст қаҳваранг шуда метавонад."),
    ("heart", "ҳарт", "дил", 3, "Body", "My heart is happy.", "Дили ман хушҳол аст."),
    ("body", "боди", "бадан", 3, "Body", "Take care of your body.", "Баданатро нигоҳубин кун."),
    ("hug", "ҳаг", "оғӯш", 3, "Family", "Give me a hug.", "Маро оғӯш кун."),
    ("kiss", "кис", "бӯса", 3, "Family", "A kiss for mum.", "Барои модар як бӯса."),
    ("people we love", "пипл уи лав", "наздикон", 3, "Family", "We love our family.", "Мо оиларо дӯст медорем."),
    ("us", "ас", "мо (ба мо)", 3, "Basics", "Come with us.", "Бо мо биё."),
    # week 4 +20
    ("lion", "лайон", "шер", 4, "Animals", "The lion is big.", "Шер калон аст."),
    ("tiger", "тайгер", "паланг", 4, "Animals", "A tiger has stripes.", "Паланг хат дорад."),
    ("elephant", "элифант", "фил", 4, "Animals", "The elephant is huge.", "Фил хеле калон аст."),
    ("monkey", "манки", "маймун", 4, "Animals", "The monkey can jump.", "Маймун ҷаҳида метавонад."),
    ("bear", "бээр", "хирс", 4, "Animals", "The bear is strong.", "Хирс қувваманд аст."),
    ("zebra", "зибра", "зебра", 4, "Animals", "A zebra is black and white.", "Зебра сиёҳ ва сафед аст."),
    ("giraffe", "ҷираф", "заррофа", 4, "Animals", "The giraffe is tall.", "Заррофа қадбаланд аст."),
    ("snake", "снейк", "мор", 4, "Animals", "The snake is long.", "Мор дароз аст."),
    ("frog", "фрог", "қурбоққа", 4, "Animals", "The frog can jump.", "Қурбоққа ҷаҳида метавонад."),
    ("bee", "би", "занбӯр", 4, "Animals", "A bee makes honey.", "Занбӯр асал месозад."),
    ("ant", "энт", "мӯрча", 4, "Animals", "An ant is small.", "Мӯрча хурд аст."),
    ("butterfly", "баттерфлай", "шапарак", 4, "Animals", "A butterfly is pretty.", "Шапарак зебо аст."),
    ("whale", "уэйл", "кит", 4, "Animals", "The whale is in the sea.", "Кит дар баҳр аст."),
    ("dolphin", "долфин", "делфин", 4, "Animals", "Dolphins can swim.", "Делфинҳо шино карда метавонанд."),
    ("fox", "фокс", "рӯбоҳ", 4, "Animals", "The fox is clever.", "Рӯбоҳ зирак аст."),
    ("wolf", "вулф", "гург", 4, "Animals", "The wolf lives in the forest.", "Гург дар ҷангал зиндагӣ мекунад."),
    ("camel", "камэл", "шутур", 4, "Animals", "A camel lives in the desert.", "Шутур дар биёбон зиндагӣ мекунад."),
    ("panda", "панда", "панда", 4, "Animals", "The panda eats bamboo.", "Панда бамбук мехӯрад."),
    ("zoo", "зу", "боғи ҳайвонот", 4, "Animals", "We go to the zoo.", "Мо ба боғи ҳайвонот меравем."),
    ("wild", "уайлд", "ваҳшӣ", 4, "Animals", "A lion is a wild animal.", "Шер ҳайвони ваҳшӣ аст."),
    # week 5 +10
    ("breakfast", "брэкфаст", "наҳорӣ", 5, "Food", "I eat breakfast.", "Ман наҳорӣ мехӯрам."),
    ("lunch", "ланч", "хӯроки нисфирӯзӣ", 5, "Food", "Lunch is ready.", "Хӯроки нисфирӯзӣ тайёр аст."),
    ("dinner", "диннер", "хӯроки шом", 5, "Food", "Dinner is at seven.", "Шом соати ҳафт аст."),
    ("cake", "кейк", "торт", 5, "Food", "The cake is sweet.", "Торт ширин аст."),
    ("cookie", "куки", "печенье", 5, "Food", "I like a cookie.", "Ба ман печенье маъқул аст."),
    ("sugar", "шугар", "қанд", 5, "Food", "Less sugar, please.", "Қанди камтар, лутфан."),
    ("salt", "солт", "намак", 5, "Food", "Add a little salt.", "Каме намак андоз."),
    ("sweet", "суит", "ширин", 5, "Food", "Honey is sweet.", "Асал ширин аст."),
    ("plate", "плейт", "табақ", 5, "Food", "Put rice on the plate.", "Биринҷро ба табақ гузор."),
    ("hungry now", "ҳангри нау", "ҳозир гурусна", 5, "Food", "I am hungry now.", "Ман ҳозир гуруснаам."),
    # week 6 school/home 50
    ("school", "скул", "мактаб", 6, "School", "I go to school.", "Ман ба мактаб меравам."),
    ("classroom", "класрум", "синфхона", 6, "School", "Our classroom is bright.", "Синфхонаи мо равшан аст."),
    ("book", "бук", "китоб", 6, "School", "This is my book.", "Ин китоби ман аст."),
    ("pencil", "пэнсил", "қалам", 6, "School", "I write with a pencil.", "Ман бо қалам менависам."),
    ("paper", "пейпер", "қоғаз", 6, "School", "Draw on the paper.", "Дар қоғаз каш."),
    ("desk", "деск", "парта", 6, "School", "Sit at your desk.", "Дар парта нишин."),
    ("chair", "чеэр", "курсӣ", 6, "Home", "This chair is small.", "Ин курсӣ хурд аст."),
    ("bag", "бэг", "сумка", 6, "School", "My bag is blue.", "Сумкаам кабуд аст."),
    ("teacher", "тичер", "муаллим", 6, "School", "The teacher is kind.", "Муаллим меҳрубон аст."),
    ("student", "стюдэнт", "хонанда", 6, "School", "I am a student.", "Ман хонанда ҳастам."),
    ("lesson", "лэсн", "дарс", 6, "School", "The lesson is fun.", "Дарс шавқовар аст."),
    ("homework", "ҳоумуорк", "вазифаи хонагӣ", 6, "School", "I do my homework.", "Ман вазифаамро мекунам."),
    ("window", "уиндоу", "тиреза", 6, "Home", "Open the window.", "Тирезаро кушо."),
    ("door", "дор", "дар", 6, "Home", "Close the door.", "Дарро пӯш."),
    ("table", "тейбл", "миз", 6, "Home", "The book is on the table.", "Китоб рӯи миз аст."),
    ("bed", "бэд", "кат", 6, "Home", "I sleep in my bed.", "Ман дар кат мехобам."),
    ("room", "рум", "ҳуҷра", 6, "Home", "This is my room.", "Ин ҳуҷраи ман аст."),
    ("kitchen", "кичен", "ошхона", 6, "Home", "Mum is in the kitchen.", "Модар дар ошхона аст."),
    ("bathroom", "басрум", "ҳаммом", 6, "Home", "Wash in the bathroom.", "Дар ҳаммом шӯй."),
    ("garden", "гарден", "боғча", 6, "Home", "Flowers are in the garden.", "Гулҳо дар боғчаанд."),
    ("floor", "флор", "фарш", 6, "Home", "Sit on the floor.", "Рӯи фарш нишин."),
    ("wall", "уол", "девор", 6, "Home", "A picture on the wall.", "Дар девор расм аст."),
    ("lamp", "лэмп", "чароғ", 6, "Home", "Turn on the lamp.", "Чароғро фурӯзон кун."),
    ("phone", "фоун", "телефон", 6, "Home", "The phone is ringing.", "Телефон занг мезанад."),
    ("computer", "компьютер", "компютер", 6, "School", "I use a computer.", "Ман компютер истифода мебарам."),
    ("toy", "той", "бозича", 6, "Home", "This toy is new.", "Ин бозича нав аст."),
    ("ball", "бол", "тӯб", 6, "Home", "Kick the ball.", "Тӯбро зад."),
    ("doll", "дол", "лухтак", 6, "Home", "The doll is pretty.", "Лухтак зебо аст."),
    ("game", "гейм", "бозӣ", 6, "Home", "Let's play a game.", "Биё бозӣ кунем."),
    ("draw", "дро", "кашидан", 6, "School", "I draw a cat.", "Ман гурба мекашам."),
    ("write", "райт", "навиштан", 6, "School", "Write your name.", "Номатро нависед."),
    ("read", "рид", "хондан", 6, "School", "I read a book.", "Ман китоб мехонам."),
    ("listen", "лисн", "гӯш кардан", 6, "School", "Listen to the teacher.", "Ба муаллим гӯш кун."),
    ("speak", "спик", "гап задан", 6, "School", "Speak English.", "Англисӣ гап зан."),
    ("ask", "аск", "пурсидан", 6, "School", "Ask a question.", "Савол пурс."),
    ("answer", "ансер", "ҷавоб додан", 6, "School", "Answer the question.", "Ба савол ҷавоб деҳ."),
    ("open", "оупн", "кушодан", 6, "Home", "Open the book.", "Китобро кушо."),
    ("close", "клоуз", "пӯшидан", 6, "Home", "Close the bag.", "Сумкаро пӯш."),
    ("clean", "клин", "тоза", 6, "Home", "Keep your room clean.", "Ҳуҷраатро тоза нигоҳ дор."),
    ("dirty", "дёрти", "ифлос", 6, "Home", "The floor is dirty.", "Фарш ифлос аст."),
    ("new", "ню", "нав", 6, "Basics", "I have a new bag.", "Ман сумкаи нав дорам."),
    ("old", "олд", "кӯҳна / пир", 6, "Basics", "This book is old.", "Ин китоб кӯҳна аст."),
    ("fast", "фаст", "тез", 6, "Basics", "The car is fast.", "Мошин тез аст."),
    ("slow", "слоу", "суст", 6, "Basics", "Please speak slow.", "Лутфан суст гап зан."),
    ("quiet", "куайет", "ором", 6, "School", "Be quiet, please.", "Ором бошед, лутфан."),
    ("loud", "лауд", "баланд", 6, "School", "Do not be loud.", "Баланд гап назан."),
    ("ready", "рэди", "тайёр", 6, "School", "Are you ready?", "Ту тайёр ҳастӣ?"),
    ("start", "старт", "сархидан", 6, "School", "Let's start the lesson.", "Биё дарсро сар кунем."),
    ("finish", "финиш", "тамом кардан", 6, "School", "Finish your work.", "Коратро тамом кун."),
    ("class", "клас", "синф", 6, "School", "Our class is happy.", "Синфи мо хушҳол аст."),
    # week 7 city/nature 50
    ("city", "сити", "шаҳр", 7, "City", "I live in a city.", "Ман дар шаҳр зиндагӣ мекунам."),
    ("street", "стрит", "кӯча", 7, "City", "The street is long.", "Кӯча дароз аст."),
    ("car", "кар", "мошин", 7, "City", "The car is red.", "Мошин сурх аст."),
    ("bus", "бас", "автобус", 7, "City", "I take the bus.", "Ман бо автобус меравам."),
    ("train", "трейн", "қатора", 7, "City", "The train is fast.", "Қатора тез аст."),
    ("plane", "плейн", "ҳавопаймо", 7, "City", "The plane is in the sky.", "Ҳавопаймо дар осмон аст."),
    ("bike", "байк", "велосипед", 7, "City", "I ride a bike.", "Ман велосипед меронам."),
    ("road", "роуд", "роҳ", 7, "City", "The road is wide.", "Роҳ васеъ аст."),
    ("park", "парк", "боғ", 7, "City", "We play in the park.", "Мо дар боғ бозӣ мекунем."),
    ("tree", "три", "дарахт", 7, "Nature", "The tree is green.", "Дарахт сабз аст."),
    ("flower", "флауэр", "гул", 7, "Nature", "This flower is pretty.", "Ин гул зебо аст."),
    ("grass", "грас", "алаф", 7, "Nature", "The grass is soft.", "Алаф нарм аст."),
    ("mountain", "маунтин", "кӯҳ", 7, "Nature", "The mountain is high.", "Кӯҳ баланд аст."),
    ("river", "ривер", "дарё", 7, "Nature", "The river is long.", "Дарё дароз аст."),
    ("sea", "си", "баҳр", 7, "Nature", "The sea is blue.", "Баҳр кабуд аст."),
    ("sky", "скай", "осмон", 7, "Nature", "The sky is clear.", "Осмон соф аст."),
    ("sun", "сан", "офтоб", 7, "Nature", "The sun is hot.", "Офтоб гарм аст."),
    ("moon", "мун", "моҳ", 7, "Nature", "The moon is bright.", "Моҳ дурахшон аст."),
    ("rain", "рейн", "борон", 7, "Weather", "The rain is cold.", "Борон хунук аст."),
    ("snow", "сноу", "барф", 7, "Weather", "I like snow.", "Ба ман барф маъқул аст."),
    ("wind", "уинд", "шамол", 7, "Weather", "The wind is strong.", "Шамол сахт аст."),
    ("cloud", "клауд", "абр", 7, "Weather", "A cloud is in the sky.", "Дар осмон абр аст."),
    ("stone", "стоун", "санг", 7, "Nature", "A small stone.", "Санги хурд."),
    ("sand", "сэнд", "рег", 7, "Nature", "Sand is at the sea.", "Рег дар соҳил аст."),
    ("island", "айланд", "ҷазира", 7, "Nature", "The island is small.", "Ҷазира хурд аст."),
    ("forest", "форэст", "ҷангал", 7, "Nature", "Animals live in the forest.", "Ҳайвонот дар ҷангал зиндагӣ мекунанд."),
    ("leaf", "лиф", "барг", 7, "Nature", "A green leaf.", "Барги сабз."),
    ("shop", "шоп", "мағоза", 7, "City", "We go to the shop.", "Мо ба мағоза меравем."),
    ("market", "маркет", "бозор", 7, "City", "The market is busy.", "Бозор серодам аст."),
    ("money", "мани", "пул", 7, "City", "I have some money.", "Ман каме пул дорам."),
    ("ticket", "тикет", "чипта", 7, "City", "I need a ticket.", "Ба ман чипта лозим аст."),
    ("map", "мэп", "харита", 7, "City", "Look at the map.", "Ба харита нигар."),
    ("left", "лэфт", "чап", 7, "City", "Turn left.", "Ба чап гарда."),
    ("right", "райт", "рост", 7, "City", "Turn right.", "Ба рост гарда."),
    ("up", "ап", "боло", 7, "City", "Look up.", "Ба боло нигар."),
    ("down", "даун", "поён", 7, "City", "Sit down.", "Поён нишин."),
    ("near", "нир", "наздик", 7, "City", "The park is near.", "Боғ наздик аст."),
    ("far", "фар", "дур", 7, "City", "The mountain is far.", "Кӯҳ дур аст."),
    ("inside", "инсайд", "дар дарун", 7, "City", "Come inside.", "Ба дарун биё."),
    ("outside", "аутсайд", "берун", 7, "City", "Play outside.", "Берун бозӣ кун."),
    ("bridge", "бриҷ", "пул (роҳ)", 7, "City", "The bridge is long.", "Пул дароз аст."),
    ("hospital", "ҳоспитал", "беморхона", 7, "City", "The doctor is at the hospital.", "Духтур дар беморхона аст."),
    ("mosque", "моск", "масҷид", 7, "City", "The mosque is quiet.", "Масҷид ором аст."),
    ("village", "виллиҷ", "деҳа", 7, "City", "My grandma lives in a village.", "Бибиам дар деҳа зиндагӣ мекунад."),
    ("country", "кантри", "кишвар", 7, "City", "Tajikistan is my country.", "Тоҷикистон кишвари ман аст."),
    ("world", "уорлд", "ҷаҳон", 7, "Nature", "The world is big.", "Ҷаҳон калон аст."),
    ("earth", "ёрт", "замин", 7, "Nature", "We live on Earth.", "Мо дар Замин зиндагӣ мекунем."),
    ("fire", "файр", "оташ", 7, "Nature", "Fire is hot.", "Оташ гарм аст."),
    ("ice", "айс", "ях", 7, "Nature", "Ice is cold.", "Ях хунук аст."),
    ("shopkeeper", "шопкипер", "фӯрушанда", 7, "City", "The shopkeeper is kind.", "Фӯрушанда меҳрубон аст."),
    # week 8 time/weather/play 50
    ("morning", "морнинг", "субҳ", 8, "Time", "Good morning!", "Субҳ ба хайр!"),
    ("afternoon", "афтэрнун", "нисфирӯзӣ", 8, "Time", "See you in the afternoon.", "Нисфирӯзӣ мебинем."),
    ("evening", "ивнинг", "бегоҳ", 8, "Time", "In the evening I read.", "Бегоҳ ман мехонам."),
    ("night", "найт", "шаб", 8, "Time", "The night is quiet.", "Шаб ором аст."),
    ("day", "дей", "рӯз", 8, "Time", "Have a nice day.", "Рӯзи хуш."),
    ("week", "уик", "ҳафта", 8, "Time", "There are seven days in a week.", "Дар ҳафта ҳафт рӯз аст."),
    ("month", "манс", "моҳ (вақт)", 8, "Time", "This month is warm.", "Ин моҳ гарм аст."),
    ("year", "йир", "сол", 8, "Time", "A year has twelve months.", "Сол дувоздаҳ моҳ дорад."),
    ("hour", "ауэр", "соат (вақт)", 8, "Time", "Wait one hour.", "Як соат интизор шав."),
    ("minute", "минит", "дақиқа", 8, "Time", "One minute, please.", "Як дақиқа, лутфан."),
    ("time", "тайм", "вақт", 8, "Time", "What time is it?", "Соат чанд аст?"),
    ("early", "ёрли", "барвақт", 8, "Time", "I wake up early.", "Ман барвақт бедор мешавам."),
    ("late", "лейт", "дер", 8, "Time", "Do not be late.", "Дер накун."),
    ("yesterday", "естердей", "дирӯз", 8, "Time", "Yesterday was fun.", "Дирӯз шавқовар буд."),
    ("tomorrow", "тумороу", "фардо", 8, "Time", "See you tomorrow.", "То фардо."),
    ("always", "олвейз", "ҳамеша", 8, "Time", "I always say please.", "Ман ҳамеша «лутфан» мегӯям."),
    ("never", "нэвэр", "ҳеҷ гоҳ", 8, "Time", "Never run in class.", "Дар синф ҳеҷ гоҳ надав."),
    ("sometimes", "самтаймз", "баъзан", 8, "Time", "Sometimes I draw.", "Баъзан ман мекашам."),
    ("weather", "уэзер", "обу ҳаво", 8, "Weather", "The weather is nice.", "Обу ҳаво хуб аст."),
    ("sunny", "сани", "офтобӣ", 8, "Weather", "It is sunny today.", "Имрӯз офтобӣ аст."),
    ("cloudy", "клауди", "абрнок", 8, "Weather", "It is cloudy.", "Ҳаво абрнок аст."),
    ("rainy", "рейни", "боронӣ", 8, "Weather", "It is a rainy day.", "Рӯзи боронӣ аст."),
    ("windy", "уинди", "шамолнок", 8, "Weather", "It is windy.", "Шамолнок аст."),
    ("snowy", "сноуи", "барфӣ", 8, "Weather", "It is snowy.", "Барфӣ аст."),
    ("warm", "уорм", "гарм", 8, "Weather", "The tea is warm.", "Чой гарм аст."),
    ("cool", "кул", "хунукча", 8, "Weather", "The wind is cool.", "Шамол хунукча аст."),
    ("spring", "спринг", "баҳор", 8, "Weather", "Flowers come in spring.", "Дар баҳор гул мешукуфад."),
    ("summer", "самер", "тобистон", 8, "Weather", "Summer is hot.", "Тобистон гарм аст."),
    ("autumn", "отам", "тирамоҳ", 8, "Weather", "Leaves fall in autumn.", "Дар тирамоҳ барг мерезад."),
    ("winter", "уинтер", "зимистон", 8, "Weather", "Winter is cold.", "Зимистон хунук аст."),
    ("season", "сизн", "фасл", 8, "Weather", "What season is it?", "Кадом фасл аст?"),
    ("birthday", "бёртдей", "зодрӯз", 8, "Time", "Happy birthday!", "Зодрӯзат муборак!"),
    ("holiday", "ҳолидей", "истироҳат", 8, "Time", "Today is a holiday.", "Имрӯз рӯзи истироҳат аст."),
    ("party", "парти", "зиёфат", 8, "Time", "We have a party.", "Мо зиёфат дорем."),
    ("gift", "гифт", "тӯҳфа", 8, "Time", "This gift is for you.", "Ин тӯҳфа барои туст."),
    ("song", "сонг", "суруд", 8, "Play", "Sing a song.", "Суруд хон."),
    ("music", "мюзик", "мусиқӣ", 8, "Play", "I like music.", "Ба ман мусиқӣ маъқул аст."),
    ("dance", "дэнс", "рақс", 8, "Play", "Let's dance.", "Биё рақс кунем."),
    ("sport", "спорт", "варзиш", 8, "Play", "Sport is good.", "Варзиш хуб аст."),
    ("football", "футбол", "футбол", 8, "Play", "We play football.", "Мо футбол бозӣ мекунем."),
    ("swim", "суим", "шино кардан", 8, "Play", "I can swim.", "Ман шино карда метавонам."),
    ("ride", "райд", "савор шудан", 8, "Play", "I ride a bike.", "Ман велосипед меронам."),
    ("fly", "флай", "парвоз кардан", 8, "Play", "Birds can fly.", "Паррандаҳо парвоз мекунанд."),
    ("drive", "драйв", "рондан", 8, "Play", "Dad can drive.", "Падар ронда метавонад."),
    ("cook", "кук", "пухтан", 8, "Food", "Mum can cook.", "Модар пухта метавонад."),
    ("wash", "уош", "шустан", 8, "Home", "Wash your hands.", "Дастонатро шӯй."),
    ("brush", "браш", "шона кардан", 8, "Home", "Brush your teeth.", "Дандонатро шона кун."),
    ("watch", "уоч", "тамошо кардан", 8, "Play", "Watch the birds.", "Паррандаҳоро тамошо кун."),
    ("clock", "клок", "соат (асбоб)", 8, "Time", "Look at the clock.", "Ба соат нигар."),
    ("calendar", "календар", "тақвим", 8, "Time", "See the calendar.", "Ба тақвим нигар."),
    # week 9 community 50
    ("doctor", "доктор", "духтур", 9, "Jobs", "The doctor helps us.", "Духтур ба мо ёрӣ медиҳад."),
    ("nurse", "нёрс", "ҳамшира", 9, "Jobs", "The nurse is kind.", "Ҳамшира меҳрубон аст."),
    ("farmer", "фармер", "деҳқон", 9, "Jobs", "The farmer grows rice.", "Деҳқон биринҷ мекорад."),
    ("driver", "драйвер", "ронанда", 9, "Jobs", "The driver is careful.", "Ронанда эҳтиёткор аст."),
    ("police", "полис", "полис", 9, "Jobs", "The police help people.", "Полис ба одамон ёрӣ медиҳад."),
    ("firefighter", "файрфайтер", "оташнишон", 9, "Jobs", "A firefighter is brave.", "Оташнишон шуҷоъ аст."),
    ("singer", "сингер", "сароянда", 9, "Jobs", "The singer is loud.", "Сароянда баланд мехонад."),
    ("player", "плейер", "бозингар", 9, "Jobs", "He is a football player.", "Ӯ бозингари футбол аст."),
    ("worker", "уоркер", "коргар", 9, "Jobs", "The worker is strong.", "Коргар қувваманд аст."),
    ("job", "ҷоб", "касб", 9, "Jobs", "What is your job?", "Касби ту чист?"),
    ("work", "уорк", "кор", 9, "Jobs", "I work at home.", "Ман дар хона кор мекунам."),
    ("library", "лайбрери", "китобхона", 9, "City", "The library is quiet.", "Китобхона ором аст."),
    ("museum", "мюзиум", "осорхона", 9, "City", "We visit the museum.", "Мо ба осорхона меравем."),
    ("cinema", "синема", "кинотеатр", 9, "City", "Let's go to the cinema.", "Биё ба кино равем."),
    ("restaurant", "рэсторант", "ресторан", 9, "City", "The restaurant is busy.", "Ресторан серодам аст."),
    ("cafe", "кафе", "қаҳвахона", 9, "City", "We sit in a cafe.", "Мо дар қаҳвахона менишинем."),
    ("hotel", "ҳотел", "меҳмонхона", 9, "City", "The hotel is big.", "Меҳмонхона калон аст."),
    ("airport", "эапорт", "фурудгоҳ", 9, "City", "Planes are at the airport.", "Ҳавопаймоҳо дар фурудгоҳанд."),
    ("station", "стейшн", "истгоҳ", 9, "City", "Wait at the station.", "Дар истгоҳ интизор шав."),
    ("bank", "бэнк", "бонк", 9, "City", "The bank is closed.", "Бонк пӯшида аст."),
    ("letter", "леттер", "нома", 9, "City", "I write a letter.", "Ман нома менависам."),
    ("news", "нюз", "хабар", 9, "City", "This is good news.", "Ин хабари хуб аст."),
    ("radio", "радио", "радио", 9, "City", "Listen to the radio.", "Ба радио гӯш кун."),
    ("camera", "камера", "камера", 9, "City", "Smile for the camera.", "Барои камера табассум кун."),
    ("photo", "фото", "акс", 9, "City", "This photo is nice.", "Ин акс хуб аст."),
    ("picture", "пикчер", "расм", 9, "School", "Draw a picture.", "Расм каш."),
    ("paint", "пейнт", "ранг кардан", 9, "School", "I paint a house.", "Ман хона ранг мекунам."),
    ("story", "стори", "ҳикоя", 9, "School", "Tell me a story.", "Ба ман ҳикоя гӯ."),
    ("king", "кинг", "подшоҳ", 9, "Story", "The king is just.", "Подшоҳ адолатпеша аст."),
    ("queen", "куин", "малика", 9, "Story", "The queen is kind.", "Малика меҳрубон аст."),
    ("prince", "принс", "шоҳзода", 9, "Story", "The prince is brave.", "Шоҳзода шуҷоъ аст."),
    ("princess", "принсес", "маликаи ҷавон", 9, "Story", "The princess smiles.", "Маликаи ҷавон табассум мекунад."),
    ("castle", "касл", "қалъа", 9, "Story", "The castle is old.", "Қалъа кӯҳна аст."),
    ("magic", "мэҷик", "сеҳр", 9, "Story", "The story has magic.", "Ҳикоя сеҳр дорад."),
    ("dream", "дрим", "хоб / орзу", 9, "Story", "I have a dream.", "Ман як орзу дорам."),
    ("wish", "уиш", "хоҳиш", 9, "Story", "Make a wish.", "Хоҳиш кун."),
    ("hope", "ҳоуп", "умед", 9, "Story", "I hope you are well.", "Умедворам хуб ҳастӣ."),
    ("peace", "пис", "сулҳ", 9, "Story", "We want peace.", "Мо сулҳ мехоҳем."),
    ("rule", "рул", "қоида", 9, "School", "Follow the rule.", "Қоидаро риоя кун."),
    ("line", "лайн", "хат / саф", 9, "School", "Stand in a line.", "Дар саф ист."),
    ("circle", "сёркл", "доира", 9, "Shapes", "Draw a circle.", "Доира каш."),
    ("shape", "шейп", "шакл", 9, "Shapes", "What shape is this?", "Ин чӣ шакл аст?"),
    ("neighbor", "нейбор", "ҳамсоя", 9, "Jobs", "My neighbor is nice.", "Ҳамсояам хуб аст."),
    ("helper", "хэлпер", "ёрдамчӣ", 9, "Jobs", "Be a helper at home.", "Дар хона ёрдамчӣ бош."),
    ("team", "тим", "даста", 9, "Play", "Our team is strong.", "Дастаи мо қувваманд аст."),
    ("win", "уин", "ғолиб шудан", 9, "Play", "We can win.", "Мо ғолиб шуда метавонем."),
    ("fair", "фээр", "одилона", 9, "Play", "Play fair.", "Одилона бозӣ кун."),
    ("share", "шээр", "тақсим кардан", 9, "Play", "Share your toys.", "Бозичаҳоятро тақсим кун."),
    ("together", "тагэзер", "якҷо", 9, "Play", "We learn together.", "Мо якҷо меомӯзем."),
    ("alone", "элоун", "танҳо", 9, "Play", "Do not sit alone.", "Танҳо нанишин."),
    # week 10 verbs/grammar words 50
    ("can", "кэн", "тавонистан", 10, "Grammar", "I can run.", "Ман давида метавонам."),
    ("cannot", "кэннот", "натавонистан", 10, "Grammar", "I cannot fly.", "Ман парвоз карда наметавонам."),
    ("want", "уонт", "хостан", 10, "Grammar", "I want water.", "Ман об мехоҳам."),
    ("need", "нид", "лозим будан", 10, "Grammar", "I need a pencil.", "Ба ман қалам лозим аст."),
    ("know", "ноу", "донистан", 10, "Grammar", "I know my name.", "Ман номамро медонам."),
    ("think", "синк", "фикр кардан", 10, "Grammar", "I think it is good.", "Фикр мекунам хуб аст."),
    ("feel", "фил", "ҳис кардан", 10, "Grammar", "I feel happy.", "Ман хушҳол ҳастам."),
    ("make", "мейк", "сохтан", 10, "Verbs", "I make a cake.", "Ман торт месозам."),
    ("take", "тейк", "гирифтан", 10, "Verbs", "Take your bag.", "Сумкаатро гир."),
    ("give", "гив", "додан", 10, "Verbs", "Give me the book.", "Китобро ба ман деҳ."),
    ("put", "пут", "гузоштан", 10, "Verbs", "Put it here.", "Онро ин ҷо гузор."),
    ("find", "файнд", "ёфтан", 10, "Verbs", "Find the cat.", "Гурбаро ёб."),
    ("lose", "луз", "гум кардан", 10, "Verbs", "Do not lose your book.", "Китобатро гум накун."),
    ("keep", "кип", "нигоҳ доштан", 10, "Verbs", "Keep it safe.", "Онро бехатар нигоҳ дор."),
    ("show", "шоу", "нишон додан", 10, "Verbs", "Show me the picture.", "Расмро нишон деҳ."),
    ("tell", "тэл", "гуфтан", 10, "Verbs", "Tell me your name.", "Номатро гӯ."),
    ("call", "кол", "садо кардан", 10, "Verbs", "Call your mum.", "Модаратро садо кун."),
    ("live", "лив", "зиндагӣ кардан", 10, "Verbs", "I live in Tajikistan.", "Ман дар Тоҷикистон зиндагӣ мекунам."),
    ("grow", "гроу", "сабзидан", 10, "Verbs", "Trees grow tall.", "Дарахтон қад мекашанд."),
    ("try", "трай", "кӯшиш кардан", 10, "Verbs", "Try again.", "Боз кӯшиш кун."),
    ("begin", "бигин", "оғоз кардан", 10, "Verbs", "Begin the lesson.", "Дарсро оғоз кун."),
    ("end", "энд", "анҷом", 10, "Verbs", "This is the end.", "Ин охир аст."),
    ("use", "юз", "истифода бурдан", 10, "Verbs", "Use a pencil.", "Қаламро истифода бар."),
    ("buy", "бай", "харидан", 10, "Verbs", "I buy milk.", "Ман шир мехарам."),
    ("sell", "сэл", "фурӯхтан", 10, "Verbs", "They sell fruit.", "Онҳо мева мефурӯшанд."),
    ("pay", "пей", "пул додан", 10, "Verbs", "I pay at the shop.", "Ман дар мағоза пул медиҳам."),
    ("wear", "уэр", "пӯшидан (либос)", 10, "Verbs", "I wear a hat.", "Ман кулоҳ мепӯшам."),
    ("hold", "ҳолд", "доштан дар даст", 10, "Verbs", "Hold my hand.", "Дастамро гир."),
    ("push", "пуш", "тела додан", 10, "Verbs", "Do not push.", "Тела надиҳ."),
    ("pull", "пул", "кашидан", 10, "Verbs", "Pull the door.", "Дарро каш."),
    ("throw", "сроу", "партофтан", 10, "Verbs", "Throw the ball.", "Тӯбро парто."),
    ("catch", "кэч", "доштан / гирифтан", 10, "Verbs", "Catch the ball.", "Тӯбро дор."),
    ("kick", "кик", "задан бо по", 10, "Verbs", "Kick the ball.", "Тӯбро бо по зад."),
    ("cut", "кат", "буридан", 10, "Verbs", "Cut the paper.", "Қоғазро бур."),
    ("break", "брейк", "шикастан", 10, "Verbs", "Do not break it.", "Онро нашакан."),
    ("build", "билд", "сохтан (бино)", 10, "Verbs", "Build a house.", "Хона соз."),
    ("fix", "фикс", "таъмир кардан", 10, "Verbs", "Dad can fix it.", "Падар онро таъмир карда метавонад."),
    ("choose", "чуз", "интихоб кардан", 10, "Verbs", "Choose a book.", "Китоб интихоб кун."),
    ("remember", "римэмбер", "дар ёд доштан", 10, "Verbs", "Remember this word.", "Ин калимаро дар ёд дор."),
    ("forget", "форгет", "фаромӯш кардан", 10, "Verbs", "Do not forget homework.", "Вазифаро фаромӯш накун."),
    ("understand", "андэрстэнд", "фаҳмидан", 10, "Verbs", "I understand you.", "Ман туро мефаҳмам."),
    ("learn", "лёрн", "омӯхтан", 10, "Verbs", "I learn English.", "Ман англисӣ меомӯзам."),
    ("teach", "тич", "омӯзондан", 10, "Verbs", "Teach me please.", "Маро омӯзон, лутфан."),
    ("study", "стади", "таҳсил кардан", 10, "Verbs", "I study every day.", "Ман ҳар рӯз таҳсил мекунам."),
    ("practice", "практис", "машқ кардан", 10, "Verbs", "Practice the word.", "Калимаро машқ кун."),
    ("must", "маст", "бояд", 10, "Grammar", "You must be kind.", "Ту бояд меҳрубон бошӣ."),
    ("let", "лет", "гузоштан (иҷоза)", 10, "Grammar", "Let us learn.", "Бигузор омӯзем."),
    ("because", "бикоз", "зеро", 10, "Grammar", "I drink because I am thirsty.", "Менӯшам, зеро ташнаам."),
    ("with", "уис", "бо", 10, "Grammar", "Come with me.", "Бо ман биё."),
    ("without", "уизаут", "бе", 10, "Grammar", "Do not go without mum.", "Бе модар нарава."),
]


def example_for(english: str, tajik: str) -> tuple[str, str]:
    e = english.strip()
    return f"I like {e}.", f"Ба ман {tajik} маъқул аст."


def main() -> None:
    original = json.loads(SRC.read_text())
    assert len(original) == 150
    by_week: dict[int, list] = defaultdict(list)
    items = []
    seen_en = set()
    for i, row in enumerate(original):
        en, pron, tj, week, topic = row
        by_week[int(week)].append(i)
        day = (len(by_week[int(week)]) - 1) % 5 + 1
        items.append(
            {
                "english": en,
                "pronunciation": pron,
                "tajik": tj,
                "week": int(week),
                "topic": topic,
                "day": day,
                "difficulty": 1 if int(week) <= 2 else 2,
                "example": example_for(en, tj)[0],
                "example_tajik": example_for(en, tj)[1],
            }
        )
        seen_en.add(en.lower())
        # orange appears twice; keep both
        if en.lower() != "orange":
            pass

    extras_en = [e[0].lower() for e in EXTRAS]
    dup = [x for x in extras_en if extras_en.count(x) > 1]
    if dup:
        raise SystemExit(f"duplicate extras: {sorted(set(dup))}")
    clash = [e[0] for e in EXTRAS if e[0].lower() in seen_en and e[0].lower() != "orange"]
    if clash:
        raise SystemExit(f"clash with original: {clash}")
    if len(EXTRAS) != 350:
        raise SystemExit(f"expected 350 extras, got {len(EXTRAS)}")

    week_counts = defaultdict(int)
    for en, pron, tj, week, topic, ex, extj in EXTRAS:
        week_counts[week] += 1
        day = ((week_counts[week] - 1) % 5) + 1
        items.append(
            {
                "english": en,
                "pronunciation": pron,
                "tajik": tj,
                "week": week,
                "topic": topic,
                "day": day,
                "difficulty": 1 if week <= 2 else (2 if week <= 6 else 3),
                "example": ex,
                "example_tajik": extj,
            }
        )

    ids = [f"{w['english'].lower()}|{w['week']}|{w['tajik'].lower()}" for w in items]
    if len(ids) != 500:
        raise SystemExit(f"expected 500, got {len(ids)}")
    if len(set(ids)) != 500:
        raise SystemExit("duplicate ids")

    SRC.write_text(json.dumps(items, ensure_ascii=False, indent=2) + "\n")
    print("wrote", len(items), "words")
    for w in range(1, 11):
        print("week", w, sum(1 for x in items if x["week"] == w))


if __name__ == "__main__":
    main()
